name: Deploy CasaVue Awesome Selfhosted

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      items: ${{ steps.out_step.outputs.items}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: Download Python dependencies
        run: pip install -r requirements.txt

      - name: Generate CasaVue items config
        run: python items_config_generator.py >> config/items.yaml

      - name: Run Docker container
        run: |
          docker run --name casavue-container \
            -v $(pwd)/config:/app/config \
            ghcr.io/czoczo/cavu -static

      - name: Copy artifact from container
        run: |
          docker cp casavue-container:/app/dist/ ./dist
          docker rm casavue-container
      
      - name: Upload Artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

